export const ANALYTICS_MAX_PAGE_LIMIT = 1000
export const ANALYTICS_DEFAULT_PAGE_LIMIT = 500
export const CW_MAX = 50
export const BW_MAX = 5000
export const SAS_TOKEN_EXPIRY_MS = 15 * 60 * 1000
export const JWT_EXPIRY = '7d'
export const CACHE_TTL_MS = 5 * 60 * 1000
export const SPECIES_CACHE_KEY = 'species:all'
export const TARGET_SPECIES_COUNT = 4
export const STATES_AND_TERRITORIES_COUNT = 14
